const mongoose = require('mongoose')

const shoppingItemSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    quantity: { type: Number, default: 1 },
    unit: { type: String, default: 'item' },
    purchased: { type: Boolean, default: false },
  },
  { _id: true }
)

const shoppingListSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    name: { type: String, required: true },
    autoGenerated: { type: Boolean, default: false },
    startDate: String,
    endDate: String,
    items: [shoppingItemSchema],
  },
  { timestamps: true }
)

module.exports = mongoose.model('ShoppingList', shoppingListSchema)
