const MealPlan = require('../models/MealPlan')
const ShoppingList = require('../models/ShoppingList')

async function listShoppingLists(req, res, next) {
  try {
    const lists = await ShoppingList.find({ user: req.user.id }).sort({ createdAt: -1 })
    return res.json(lists)
  } catch (error) {
    return next(error)
  }
}

async function createManualList(req, res, next) {
  try {
    const list = await ShoppingList.create({ user: req.user.id, autoGenerated: false, ...req.body })
    return res.status(201).json(list)
  } catch (error) {
    return next(error)
  }
}

async function generateFromMealPlans(req, res, next) {
  try {
    const { name = 'Auto Shopping List', startDate, endDate } = req.body
    const plans = await MealPlan.find({ user: req.user.id, date: { $gte: startDate, $lte: endDate } })

    const aggregate = new Map()
    for (const plan of plans) {
      for (const mealType of Object.keys(plan.meals || {})) {
        for (const item of plan.meals[mealType] || []) {
          const existing = aggregate.get(item.name) || { name: item.name, quantity: 0, unit: 'serving', purchased: false }
          existing.quantity += item.servings || 1
          aggregate.set(item.name, existing)
        }
      }
    }

    const list = await ShoppingList.create({
      user: req.user.id,
      name,
      autoGenerated: true,
      startDate,
      endDate,
      items: [...aggregate.values()],
    })

    return res.status(201).json(list)
  } catch (error) {
    return next(error)
  }
}

async function toggleShoppingItem(req, res, next) {
  try {
    const { listId, itemId } = req.params
    const list = await ShoppingList.findOne({ _id: listId, user: req.user.id })
    if (!list) return res.status(404).json({ message: 'List not found' })

    const item = list.items.id(itemId)
    if (!item) return res.status(404).json({ message: 'Item not found' })
    item.purchased = !item.purchased

    await list.save()
    return res.json(list)
  } catch (error) {
    return next(error)
  }
}

module.exports = { listShoppingLists, createManualList, generateFromMealPlans, toggleShoppingItem }
